development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  database: ai_gk_development

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  database: ai_gk_production
